In [1]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# Euro 12

## Import data from datasets/euro12.csv

In [3]:
FILEPATH = "/content/drive/MyDrive/lab/data/euro12.csv"

##  Calculate the mean Yellow Cards given per Team

In [11]:
df = pd.read_csv(FILEPATH)
df.groupby("Team")["Yellow Cards"].mean()

Team
Croatia                 9.0
Czech Republic          7.0
Denmark                 4.0
England                 5.0
France                  6.0
Germany                 4.0
Greece                  9.0
Italy                  16.0
Netherlands             5.0
Poland                  7.0
Portugal               12.0
Republic of Ireland     6.0
Russia                  6.0
Spain                  11.0
Sweden                  7.0
Ukraine                 5.0
Name: Yellow Cards, dtype: float64

In [34]:
df.columns

Index(['Team', 'Goals', 'Shots on target', 'Shots off target',
       'Shooting Accuracy', '% Goals-to-shots', 'Total shots (inc. Blocked)',
       'Hit Woodwork', 'Penalty goals', 'Penalties not scored', 'Headed goals',
       'Passes', 'Passes completed', 'Passing Accuracy', 'Touches', 'Crosses',
       'Dribbles', 'Corners Taken', 'Tackles', 'Clearances', 'Interceptions',
       'Clearances off line', 'Clean Sheets', 'Blocks', 'Goals conceded',
       'Saves made', 'Saves-to-shots ratio', 'Fouls Won', 'Fouls Conceded',
       'Offsides', 'Yellow Cards', 'Red Cards', 'Subs on', 'Subs off',
       'Players Used'],
      dtype='object')

## Which teams scored more than 6 goals?

In [26]:
scores = df.groupby("Team")["Goals"].sum()
result = scores > 6
result[result == True]

Team
Germany    True
Spain      True
Name: Goals, dtype: bool

## Select the teams that start with G

In [32]:
from numpy import nan
result = df["Team"].where(df["Team"].str.startswith("G")).dropna()
result

5    Germany
6     Greece
Name: Team, dtype: object

## Present only the Shooting Accuracy from England, Italy and Russia

In [38]:
result = df.loc[df["Team"].isin(["England", "Italy", "Russia"])]
result["Shooting Accuracy"]

3     50.0%
7     43.0%
12    22.5%
Name: Shooting Accuracy, dtype: object

# Drinks

## Read and save data from datasets/drinks.txt

In [41]:
FILEPATH = "/content/drive/MyDrive/lab/data/drinks.csv"
df_drink = pd.read_csv(FILEPATH)

In [47]:
df_drink.columns

Index(['country', 'beer_servings', 'spirit_servings', 'wine_servings',
       'total_litres_of_pure_alcohol', 'continent'],
      dtype='object')

## Which continent drinks more beer on average?

In [63]:
df_drink.groupby("continent")["total_litres_of_pure_alcohol"].mean()
result = df_drink.groupby("continent")["total_litres_of_pure_alcohol"].mean()
result[result == result.max()]

continent
EU    8.617778
Name: total_litres_of_pure_alcohol, dtype: float64

## For each continent print the statistics for wine consumption.

In [64]:
df_drink.groupby("continent")["wine_servings"].describe()

           count        mean        std  min   25%    50%     75%    max
continent
AF          53.0   16.264151  38.846419  0.0   1.0    2.0   13.00  233.0
AS          44.0    9.068182  21.667034  0.0   0.0    1.0    8.00  123.0
EU          45.0  142.222222  97.421738  0.0  59.0  128.0  195.00  370.0
OC          16.0   35.625000  64.555790  0.0   1.0    8.5   23.25  212.0
SA          12.0   62.416667  88.620189  1.0   3.0   12.0   98.50  221.0

##  Print the mean, min and max values for spirit consumption per continent.

In [65]:
result = df_drink.groupby("continent")["spirit_servings"].agg(["mean", "min", "max"])
result

                 mean  min  max
continent
AF          16.339623    0  152
AS          60.840909    0  326
EU         132.555556    0  373
OC          58.437500    0  254
SA         114.750000   25  302